filebeat.inputs:
  - type: filestream
    id: django-logs
    enabled: true
    paths:
      - /usr/share/filebeat/logs/app.log
    parsers:
      - ndjson:
          overwrite_keys: true
          add_error_key: true
    data_stream:
      type: logs
      dataset: django.app
      namespace: default
    fields:
      log_type: django
    fields_under_root: true

filebeat.data_streams.enabled: true
setup.ilm.enabled: false

setup.template.name: "django-logs"
setup.template.pattern: "django-logs-*"

output.elasticsearch:
  hosts: ["http://elastic:9200"]
  index: "django-logs-%{+yyyy.MM.dd}"

setup.kibana:
  host: "http://kibana:5601"

logging:
  level: info
  to_files: true
  files:
    path: /usr/share/filebeat/logs
    name: filebeat
    keepfiles: 7
    permissions: 0644
