filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/app/*.log
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "filebeat-django-%{+yyyy.MM.dd}"

setup.kibana:
  host: "http://kibana:5601"

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~
