version: '3.9'

services:
  web:
    build: .
    command: ["sh", "/app/entrypoint.sh"]
    environment:
      ELASTICSEARCH_HOST: http://elastic:9200
    volumes:
      - .:/app
      - ./logs:/logs
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elastic
    networks:
      - elk
      - services
    mem_limit: 1g

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: invoice_db
      POSTGRES_USER: invoice_user
      POSTGRES_PASSWORD: invoice_pass
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - services
    mem_limit: 1g

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticdata:/var/lib/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    mem_limit: 2g
      
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: "http://elastic:9200"
    depends_on:
      - elastic
    ports:
      - "5601:5601"
    networks:
      - elk
    mem_limit: 2g
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
  
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.1
    container_name: filebeat
    user: root
    volumes:
      - ./services/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/usr/share/filebeat/logs
      - filebeat-data:/usr/share/filebeat/data
    depends_on:
      - elastic
      - kibana
    mem_limit: 1g
    entrypoint: >
      /bin/sh -c "
      until curl -s http://elastic:9200 >/dev/null; do
        echo 'Waiting for Elasticsearch...';
        sleep 5;
      done;
      until curl -s http://kibana:5601/api/status | grep -q '\"summary\":\"All services are available\"'; do
        echo 'Waiting for Kibana...';
        sleep 5;
      done;
      filebeat setup --strict.perms=false;
      filebeat -e --strict.perms=false"
    networks:
      - elk

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - services

  celery:
    build: .
    entrypoint: ["/bin/sh", "-c", "chmod 600 InvoiceBrain/.pgpass && chmod 600 InvoiceBrain/.pg_service.conf && celery -A InvoiceBrain worker --loglevel=info"]
    volumes:
      - .:/code
      - ./logs:/logs
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - services

  celery-beat:
    build: .
    command: celery -A InvoiceBrain beat --loglevel=info
    volumes:
      - .:/app
      - ./logs:/logs
    depends_on:
      - redis
      - web
      - celery
    networks:
      - services

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - services

volumes:
  pgdata:
  elasticdata:
  filebeat-data:

networks:
  elk:
  services: