version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      ELASTICSEARCH_HOST: http://elastic:9200
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - elk
      - services

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: invoice_db
      POSTGRES_USER: invoice_user
      POSTGRES_PASSWORD: invoice_pass
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - services

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=changeme
      - KIBANA_PASSWORD=changeme
    volumes:
      - elasticdata:/var/lib/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    mem_limit: 2g
      
  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.0
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOST: "http://elastic:9200"
    depends_on:
      - elastic
    ports:
      - "5601:5601"
    networks:
      - elk
    mem_limit: 1g
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - services

  celery:
    build: .
    command: celery -A InvoiceBrain worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - services

volumes:
  pgdata:
  elasticdata:

networks:
  elk:
  services: