# Generated by Django 5.2.1 on 2025-05-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='paument_due_date',
            new_name='payment_due_date',
        ),
    ]
