# Generated by Django 5.2.1 on 2025-05-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_description_invoice_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sended_overdude_notification_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
