# Generated by Django 5.2.1 on 2025-05-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_sended_overdude_notification_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='products',
            field=models.JSONField(default=dict),
        ),
    ]
